### ISSUE TITLE
Release a 1.0.1?

### ISSUE THREAD

**Issue by fnordfish** [9to5/pushr-core#10]
It's been a view month since the last commit on the develop branch. It would be great if you could release the last changes somehow. Either a 1.0.1, or 1.0.1-pre would be fine - pulling dependencies from git repositories isn't much fun ;)
(I'm particularly interested in 12e7446be)

Thanks a lot!

**Comment by tompesman** [comment]
Here you are: https://github.com/9to5/pushr-core/commit/3b26a9c6f6795b627e9cc31c1668c8ba6030292c Version 1.0.1 is released to rubygems.org. Enjoy!

pushr-core + pushr-apns + pushr-gcm are now all on 1.0.1.

**Comment by fnordfish** [comment]
Thanks a lot!
