### ISSUE TITLE
How to load Rails ActiveRecord in feedback_processor.rb

### ISSUE THREAD

**Issue by jim0020** [9to5/pushr-core#11]
I need to access Rails ActiveRecord in my feedback_processor.rb (and perhaps the stats_processor too).   It seems like the rails environment is not loaded for pushr-core, but it was in push-core.  How can I load the rails environment for use in the feedback_processor.rb?  I need to use the feedback to remove or update devices in my rails database.

**Comment by tompesman** [comment]
check:
https://github.com/9to5/pushr-core/blob/develop/lib/generators/templates/feedback_processor.rb

Do you have the line in initializer?

**Comment by jim0020** [comment]
Tom,
   Thanks.  Was missing intializer entirely.  I was using the same feedback_processor.rb from my main branch using push-core which never had an intializer.  I guess I should have compared feedback_processor.rb between push and pushr more carefully.  :-)  

  Hey, any thoughts on putting the redis path setting in the yml?

Jim

**Comment by tompesman** [comment]
Nice!

Regarding the Redis settings in the YAML file, I think it's a bit messy. Right now the information in the yaml file are the push configurations. Redis you can configure using the command line and using the ENV variables, do we need a third option?

**Comment by jim0020** [comment]
The issue was actually with bundler.  Was running bundler v1.6.x, upgrading to 1.8.5 solved the problem.
