### ISSUE TITLE
Using absolute path for pushr daemon pid file doesn't create the file.

### ISSUE THREAD

**Issue by jim0020** [9to5/pushr-core#12]
bundle exec pushr -o localhost -r 6379 -p /my_home_dir_path/my_project_dir/config/pushr_daemon.pid 

doesn't create the pid file, but 

bundle exec pushr -o localhost -r 6379 -p config/pushr_daemon.pid 

does create the pid file.

**Comment by tompesman** [comment]
https://github.com/9to5/pushr-core/blob/develop/lib/pushr/daemon/settings.rb#L16

I think there should be and `else` here...

**Comment by jim0020** [comment]
Thanks Tom,   I’d have investigated more, but up to my eyeballs right now…

Jim

**Comment by tompesman** [comment]
version 1.0.2 released! :shipit:
